football_league_list:
    path: /football-league
    requirements:
        _method: GET
    controller: App\Controller\FootballLeagueController::list
football_league_single:
    path: /football-league/{id}
    requirements:
        _method: GET
    controller: App\Controller\FootballLeagueController::single
